INSERT INTO bl_city VALUES(1,'Araba/Álava', 1);
INSERT INTO bl_city VALUES(2,'Albacete', 2);
INSERT INTO bl_city VALUES(3,'Alicante', 3);
INSERT INTO bl_city VALUES(4,'Almería', 4);
INSERT INTO bl_city VALUES(5,'Ávila', 5);
INSERT INTO bl_city VALUES(6,'Badajoz', 6);
INSERT INTO bl_city VALUES(7,'Balearic Islands', 7);
INSERT INTO bl_city VALUES(8,'Barcelona', 8);
INSERT INTO bl_city VALUES(9,'Burgos', 9);
INSERT INTO bl_city VALUES(10,'Cáceres', 10);
INSERT INTO bl_city VALUES(11,'Cádiz', 11);
INSERT INTO bl_city VALUES(12,'Castellón', 12);
INSERT INTO bl_city VALUES(13,'Ciudad Real', 13);
INSERT INTO bl_city VALUES(14,'Córdoba', 14);
INSERT INTO bl_city VALUES(15,'A Coruña', 15);
INSERT INTO bl_city VALUES(16,'Cuenca', 16);
INSERT INTO bl_city VALUES(17,'Girona', 17);
INSERT INTO bl_city VALUES(18,'Granada', 18);
INSERT INTO bl_city VALUES(19,'Guadalajara', 19);
INSERT INTO bl_city VALUES(20,'Gipuzkoa', 20);
INSERT INTO bl_city VALUES(21,'Huelva', 21);
INSERT INTO bl_city VALUES(22,'Huesca', 22);
INSERT INTO bl_city VALUES(23,'Jaén', 23);
INSERT INTO bl_city VALUES(24,'León', 24);
INSERT INTO bl_city VALUES(25,'Lleida', 25);
INSERT INTO bl_city VALUES(26,'Lugo', 26);
INSERT INTO bl_city VALUES(27,'Madrid', 27);
INSERT INTO bl_city VALUES(28,'Málaga', 28);
INSERT INTO bl_city VALUES(29,'Murcia', 29);
INSERT INTO bl_city VALUES(30,'Navarre', 30);
INSERT INTO bl_city VALUES(31,'Ourense', 31);
INSERT INTO bl_city VALUES(32,'Palencia', 32);
INSERT INTO bl_city VALUES(33,'Las Palmas', 33);
INSERT INTO bl_city VALUES(34,'Pontevedra', 34);
INSERT INTO bl_city VALUES(35,'Salamanca', 35);
INSERT INTO bl_city VALUES(36,'Santa Cruz de Tenerife', 36);
INSERT INTO bl_city VALUES(37,'Segovia', 37);
INSERT INTO bl_city VALUES(38,'Seville', 38);
INSERT INTO bl_city VALUES(39,'Soria', 39);
INSERT INTO bl_city VALUES(40,'Tarragona', 40);
INSERT INTO bl_city VALUES(41,'Teruel', 41);
INSERT INTO bl_city VALUES(42,'Toledo', 42);
INSERT INTO bl_city VALUES(43,'Valencia', 43);
INSERT INTO bl_city VALUES(44,'Valladolid', 44);
INSERT INTO bl_city VALUES(45,'Bizkaia', 45);
INSERT INTO bl_city VALUES(46,'Zamora', 46);
INSERT INTO bl_city VALUES(47,'Zaragoza', 47);
INSERT INTO bl_city VALUES(48,'Ceuta', 48);
INSERT INTO bl_city VALUES(49,'Melilla', 49);