/*!40000 ALTER TABLE `bl_subcategory` DISABLE KEYS */;
INSERT INTO bl_subcategory VALUES(1,1,'Amazon Prime Video',1);
INSERT INTO bl_subcategory VALUES(2,2,'Todos los videos',2);
INSERT INTO bl_subcategory VALUES(3,3,'Películas',3);
INSERT INTO bl_subcategory VALUES(4,4,'Series',4);
INSERT INTO bl_subcategory VALUES(5,5,'Amazon Music',5);
INSERT INTO bl_subcategory VALUES(6,6,'Amazon Music Unlimited',6);
INSERT INTO bl_subcategory VALUES(7,7,'Prime Music',7);
INSERT INTO bl_subcategory VALUES(8,8,'Abrir el lector Web',8);
INSERT INTO bl_subcategory VALUES(9,9,'Descargar nuestras aplicaciones',9);
INSERT INTO bl_subcategory VALUES(10,10,'CDs & Vinilos',10);
INSERT INTO bl_subcategory VALUES(11,1,'Tienda de Música digital',11);
INSERT INTO bl_subcategory VALUES(12,2,'Amazon Photos',12);
INSERT INTO bl_subcategory VALUES(13,3,'Amazon Photos',13);
INSERT INTO bl_subcategory VALUES(14,4,'Amazon Drive',14);
INSERT INTO bl_subcategory VALUES(15,5,'Descarga las aplicaciones gratuitas',15);
INSERT INTO bl_subcategory VALUES(16,6,'Inicia sesión',16);
INSERT INTO bl_subcategory VALUES(17,7,'Echo y Alexa',17);
INSERT INTO bl_subcategory VALUES(18,8,'Nuevo Echo Dot',18);
INSERT INTO bl_subcategory VALUES(19,9,'Nuevo Amazon Echo',19);
INSERT INTO bl_subcategory VALUES(20,1,'Nuevo Echo Plus',20);
INSERT INTO bl_subcategory VALUES(21,1,'Nuevo Echo Spot',21);
INSERT INTO bl_subcategory VALUES(22,2,'Nuevo Echo Show',22);
INSERT INTO bl_subcategory VALUES(23,3,'Descubre todos los dispositivos con Alexa',23);
INSERT INTO bl_subcategory VALUES(24,4,'Conoce a Alexa',24);
INSERT INTO bl_subcategory VALUES(25,5,'App Alexa',25);
INSERT INTO bl_subcategory VALUES(26,6,'Alexa y Hogar digital',26);
INSERT INTO bl_subcategory VALUES(27,7,'Todas las Skills',27);
INSERT INTO bl_subcategory VALUES(28,8,'Amazon Music Unlimited',28);
INSERT INTO bl_subcategory VALUES(29,9,'E-readers y eBooks Kindle',29);
INSERT INTO bl_subcategory VALUES(30,1,'Kindle',30);
INSERT INTO bl_subcategory VALUES(31,1,'Nuevo Kindle Paperwhite',31);
INSERT INTO bl_subcategory VALUES(32,2,'Kindle Oasis',32);
INSERT INTO bl_subcategory VALUES(33,3,'Accesorios',33);
INSERT INTO bl_subcategory VALUES(34,4,'eBooks Kindle',34);
INSERT INTO bl_subcategory VALUES(35,5,'Kindle Unlimited',35);
INSERT INTO bl_subcategory VALUES(36,6,'¡Nuevo! Prime Reading',36);
INSERT INTO bl_subcategory VALUES(37,7,'Kindle Flash',37);
INSERT INTO bl_subcategory VALUES(38,8,'Apps de Kindle gratuitas',38);
INSERT INTO bl_subcategory VALUES(39,9,'Kindle Cloud Reader',39);
INSERT INTO bl_subcategory VALUES(40,1,'Gestionar contenido y dispositivos',40);
INSERT INTO bl_subcategory VALUES(41,1,'Tablets Fire',41);
INSERT INTO bl_subcategory VALUES(42,2,'Fire 7',42);
INSERT INTO bl_subcategory VALUES(43,3,'Nuevo Fire HD 8',43);
INSERT INTO bl_subcategory VALUES(44,4,'Accesorios',44);
INSERT INTO bl_subcategory VALUES(45,5,'Apps',45);
INSERT INTO bl_subcategory VALUES(46,6,'Juegos',46);
INSERT INTO bl_subcategory VALUES(47,7,'Música digital',47);
INSERT INTO bl_subcategory VALUES(48,8,'eBooks Kindle',48);
INSERT INTO bl_subcategory VALUES(49,9,'Gestionar contenido y dispositivos',49);
INSERT INTO bl_subcategory VALUES(50,1,'Amazon Fire TV',50);
INSERT INTO bl_subcategory VALUES(51,1,'Fire TV Stick | Basic Edition',51);
INSERT INTO bl_subcategory VALUES(52,2,'Apps y juegos para Fire TV Stick',52);
INSERT INTO bl_subcategory VALUES(53,3,'Prime Video',53);
INSERT INTO bl_subcategory VALUES(54,4,'Amazon Drive',54);
INSERT INTO bl_subcategory VALUES(55,5,'Appstore para Android',55);
INSERT INTO bl_subcategory VALUES(56,6,'Apps',56);
INSERT INTO bl_subcategory VALUES(57,7,'Juegos',57);
INSERT INTO bl_subcategory VALUES(58,8,'Amazon Coins',58);
INSERT INTO bl_subcategory VALUES(59,9,'Aplicaciones Amazon',59);
INSERT INTO bl_subcategory VALUES(60,0,'Mis aplicaciones y suscripciones',60);
INSERT INTO bl_subcategory VALUES(61,1,'Libros',61);
INSERT INTO bl_subcategory VALUES(62,2,'Libros',62);
INSERT INTO bl_subcategory VALUES(63,3,'eBooks Kindle',63);
INSERT INTO bl_subcategory VALUES(64,4,'Kindle Unlimited',64);
INSERT INTO bl_subcategory VALUES(65,5,'¡Nuevo! Prime Reading',65);
INSERT INTO bl_subcategory VALUES(66,6,'Libros en inglés',66);
INSERT INTO bl_subcategory VALUES(67,7,'Libros en idiomas extranjeros',67);
INSERT INTO bl_subcategory VALUES(68,8,'Libros infantiles y juveniles',68);
INSERT INTO bl_subcategory VALUES(69,9,'Libros de texto y universitarios',69);
INSERT INTO bl_subcategory VALUES(70,1,'Cine, TV y Música',70);
INSERT INTO bl_subcategory VALUES(71,1,'Todo en Cine y TV',71);
INSERT INTO bl_subcategory VALUES(72,2,'Series TV',72);
INSERT INTO bl_subcategory VALUES(73,3,'Blu-ray',73);
INSERT INTO bl_subcategory VALUES(74,4,'CDs y vinilos',74);
INSERT INTO bl_subcategory VALUES(75,5,'Amazon Music Unlimited',75);
INSERT INTO bl_subcategory VALUES(76,6,'Prime Music',76);
INSERT INTO bl_subcategory VALUES(77,7,'Música digital',77);
INSERT INTO bl_subcategory VALUES(78,8,'Instrumentos musicales',78);
INSERT INTO bl_subcategory VALUES(79,9,'Electrónica',79);
INSERT INTO bl_subcategory VALUES(80,1,'Fotografía y videocámaras',80);
INSERT INTO bl_subcategory VALUES(81,1,'Móviles y telefonía',81);
INSERT INTO bl_subcategory VALUES(82,2,'TV, Vídeo y Home Cinema',82);
INSERT INTO bl_subcategory VALUES(83,3,'Audio y Hi-Fi',83);
INSERT INTO bl_subcategory VALUES(84,4,'GPS',84);
INSERT INTO bl_subcategory VALUES(85,5,'Instrumentos musicales',85);
INSERT INTO bl_subcategory VALUES(86,6,'Accesorios de electrónica',86);
INSERT INTO bl_subcategory VALUES(87,7,'Informática',87);
INSERT INTO bl_subcategory VALUES(88,8,'Hogar Digital',88);
INSERT INTO bl_subcategory VALUES(89,9,'Amazon Renewed',89);
INSERT INTO bl_subcategory VALUES(90,1,'Todo en Electrónica',90);
INSERT INTO bl_subcategory VALUES(91,1,'Informática y Oficina',91);
INSERT INTO bl_subcategory VALUES(92,2,'Portátiles',92);
INSERT INTO bl_subcategory VALUES(93,3,'Tablets',93);
INSERT INTO bl_subcategory VALUES(94,4,'Sobremesas',94);
INSERT INTO bl_subcategory VALUES(95,5,'Monitores',95);
INSERT INTO bl_subcategory VALUES(96,6,'Componentes',96);
INSERT INTO bl_subcategory VALUES(97,7,'Accesorios de informática',97);
INSERT INTO bl_subcategory VALUES(98,8,'Impresoras y tinta',98);
INSERT INTO bl_subcategory VALUES(99,9,'Software',99);
INSERT INTO bl_subcategory VALUES(100,1,'Gaming',100);