/*!40000 ALTER TABLE `bl_district` DISABLE KEYS */;
INSERT INTO bl_district VALUES(1,'Alicante',1);
INSERT INTO bl_district VALUES(2,'Catral',2);
INSERT INTO bl_district VALUES(3,'Daya Nueva',3);
INSERT INTO bl_district VALUES(4,'Almoradí',4);
INSERT INTO bl_district VALUES(5,'Algorfa',5);
INSERT INTO bl_district VALUES(6,'Rojales',6);
INSERT INTO bl_district VALUES(7,'San Fulgencio',7);
INSERT INTO bl_district VALUES(8,'Benijófar',8);
INSERT INTO bl_district VALUES(9,'Formentera del Segura',9);
INSERT INTO bl_district VALUES(10,'Torrevieja',10);
INSERT INTO bl_district VALUES(11,'Los Montesinos',11);
INSERT INTO bl_district VALUES(12,'Orihuela-Costa',12);
INSERT INTO bl_district VALUES(13,'Pilar de ,la Horadada',13);
INSERT INTO bl_district VALUES(14,'San Miguel ,de Salinas',14);
INSERT INTO bl_district VALUES(15,'La Marina',15);
INSERT INTO bl_district VALUES(16,'El Altet',16);
INSERT INTO bl_district VALUES(17,'Elche',17);
INSERT INTO bl_district VALUES(18,'Orihuela',18);
INSERT INTO bl_district VALUES(19,'Jacarilla',19);
INSERT INTO bl_district VALUES(20,'La Aparecida',20);
INSERT INTO bl_district VALUES(21,'Los Desamprados',21);
INSERT INTO bl_district VALUES(22,'Hurchillo',22);
INSERT INTO bl_district VALUES(23,'San Bartolome',23);
INSERT INTO bl_district VALUES(24,'Los Perez',24);
INSERT INTO bl_district VALUES(25,'Benferri',25);
INSERT INTO bl_district VALUES(26,'Los Monteros',26);
INSERT INTO bl_district VALUES(27,'Los Vicentes',27);
INSERT INTO bl_district VALUES(28,'Entre Naranjos',28);
INSERT INTO bl_district VALUES(29,'Torrellano',29);
INSERT INTO bl_district VALUES(30,'Crevillent',30);
INSERT INTO bl_district VALUES(31,'Albatera',31);
INSERT INTO bl_district VALUES(32,'San Isidro',32);
INSERT INTO bl_district VALUES(33,'Callosa de Segura',33);
INSERT INTO bl_district VALUES(34,'Villena',34);
INSERT INTO bl_district VALUES(35,'Beneixama',35);
INSERT INTO bl_district VALUES(36,'Benidorm',36);
INSERT INTO bl_district VALUES(37,'Elda',37);
INSERT INTO bl_district VALUES(38,'Petrer',38);
INSERT INTO bl_district VALUES(39,'San Vicente del Raspeig',39);
INSERT INTO bl_district VALUES(40,'Denia',40);
INSERT INTO bl_district VALUES(41,'Calpe',41);
INSERT INTO bl_district VALUES(42,'Alcoy',42);
INSERT INTO bl_district VALUES(43,'La Nucia',43);
INSERT INTO bl_district VALUES(44,'Benidoleig',44);
INSERT INTO bl_district VALUES(45,'Javea',45);
INSERT INTO bl_district VALUES(46,'Parcent',46);